# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.todoEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.todoEdit.setGeometry(QtCore.QRect(30, 390, 731, 31))
        self.todoEdit.setObjectName("todoEdit")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(22, 440, 741, 41))
        self.addButton.setObjectName("addButton")
        self.todoView = QtWidgets.QListView(parent=self.centralwidget)
        self.todoView.setGeometry(QtCore.QRect(30, 10, 721, 192))
        self.todoView.setObjectName("todoView")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 250, 701, 80))
        self.widget.setObjectName("widget")
        self.deleteButton = QtWidgets.QPushButton(parent=self.widget)
        self.deleteButton.setGeometry(QtCore.QRect(10, 20, 311, 41))
        self.deleteButton.setObjectName("deleteButton")
        self.completeButton = QtWidgets.QPushButton(parent=self.widget)
        self.completeButton.setGeometry(QtCore.QRect(380, 20, 311, 41))
        self.completeButton.setObjectName("completeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setText(_translate("MainWindow", "Add Todo"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.completeButton.setText(_translate("MainWindow", "Complete"))
